### ISSUE TITLE
Automatically warn if user has different ports set up

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/mm-plugin#24]
Not useful for prod, but for the beta, could be helpful for debugging.

**Comment by filips123** [comment]
Would it be possible to automatically detect used port and use it without any errors?

**Comment by danfinlay** [comment]
There are three places port exists today:

- The `mm-config.json`, which is only used for the `mm-plugin serve` command, which is really just a development tool for quickly hosting the current directory on that port.
- The `index.html`, which is really just your front-end. In practice this will need to be a variable that is configured by environment. In production you want one value, in development you may just want the one that is used in `.mm-config`.
- The `package.json`, which again should be configured by environment.

This is probably a good argument for having an `environments` key in the `mm-config.json` file, which could be used to swap out some string in the `index.html` and `package.json` files, unifying the port to one place, and avoiding configuration errors in turn.

This sounds a little bit hacky though, since it seems possibly over-tailored to the very simple example format.

I'd love to hear ideas for how we could provide this environmental config in a more project-agnostic way.

**Comment by rekmarks** [comment]
Through recent changes, this has been resolved. The port is listed in two places, but `mm-plugin.config.json` is the single source of truth, as the value in `package.json` is derived therefrom (or just uses the default: `8081`). See the [changelog](https://github.com/MetaMask/mm-plugin/blob/master/CHANGELOG.md) for more details.
