### ISSUE TITLE
Build errors should not break watch script

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/mm-plugin#32]
Currently, a build error will interrupt the watch cycle.

Reproduction steps:
- `mkdir test && cd test && mm-plugin init` to setup
- `mm-plugin watch` to use watch script
- Edit `index.js` to have some invalid JS.
- Observe watch script breaks.

Desired behavior:

Watch script should report errors, but be ready to retry on file change still.

**Comment by rekmarks** [comment]
Fixed in `0.3.4`
