### ISSUE TITLE
mm-plugin install conflicts with existing package.json

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/mm-plugin#38]
Steps to reproduce:

- Start with your own package.json
- `yarn add mm-plugin -D` to install mm-plugin as a dev dependency
- run `yarn mm-plugin init` to run the mm-plugin 

Problems:
- Notice all of the `mm-plugin` (dev dependencies) are flattened and added to `dependencies`
- Notice `undefined` is added as a prefix to all dependency versions.

Found by @whymarrh

**Comment by rekmarks** [comment]
This is due to `mm-plugin` using  the `init` module of from the `npm` CLI. Working on a fix.

**Comment by rekmarks** [comment]
Fixed by https://github.com/MetaMask/mm-plugin/commit/436b635c36c3469b24b0059ed69b2eaa7ca8733b
